
export declare const User: FC;
export declare const People: FC;
export { default as MyButton } from '../components/MyButton';
export declare const FormContent: FC;
export declare const ImageUpload: FC;
export declare const MyInputNumber: FC;
export declare const MyDatePicker: FC;
export declare const MyRangePicker: FC;
export declare const SearchInput: FC;
export declare const SearchTop: FC;
export declare const StaticSelect: FC;
export declare const StaticTabs: FC;
export declare const ComImg: FC;
export declare const RadioButtons: FC;
export declare const MySwitch: FC;
export declare const SpuInfo: FC;
export type { appStateProps } from '../utils/appState';
export { default as appState } from '../utils/appState';
export { default as initEnv } from '../utils/initEnv';
export declare const theme: object;
